---
esphome:
  name: picow-blink

rp2040:
  board: rpipicow

# Enable logging
logger:
  level: DEBUG

# https://esphome.io/components/light/rp2040_pio_led_strip.html
light:
  - platform: rp2040_pio_led_strip
    name: your_preferred_name
    id: led_strip
    pin: GPIO15
    num_leds: 50
    pio: 0
    rgb_order: RGB
    chipset: WS2812
    # chipset: WS2812B


# for Pico W (different GPIO)
output:
  - platform: gpio
    pin: 32
    id: led

interval:
  - interval: 1000ms
    then:
      - output.turn_on: led
      - delay: 500ms
      - output.turn_off: led

# # Dimmable
# output:
#   - platform: rp2040_pwm
#     pin: 15
#     id: led

# light:
#   - platform: monochromatic
#     name: "Dimmable LED"
#     output: led

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"

wifi:
  ssid: !secret wifi1_ssid
  password: !secret wifi1_password
